import {api,setCsrf,errorMessage} from './api.js';
import {element,renderBoard,renderTask} from './views.js';
const $=selector=>document.querySelector(selector);
let user=null,projects=[],project=null,view=null;const drafts=new Map();
function message(error){$('#global-message').textContent=errorMessage(error);}
function loggedOut(){user=null;projects=[];project=null;view=null;drafts.clear();setCsrf('');for(const dialog of document.querySelectorAll('dialog[open]'))dialog.close();$('#workspace-view').hidden=true;$('#login-view').hidden=false;$('#project-list').replaceChildren();$('#board').replaceChildren();$('#comments').replaceChildren();$('#delivery').replaceChildren();$('#comment-form').reset();}
async function submit(form,operation){const buttons=[...form.querySelectorAll('button[type=submit]')];if(buttons.some(b=>b.disabled))return;buttons.forEach(b=>b.disabled=true);const error=form.querySelector('[role=alert]');if(error)error.textContent='';try{await operation();}catch(e){if(error)error.textContent=errorMessage(e);else message(e);}finally{buttons.forEach(b=>b.disabled=false);}}
function navigation(){const nav=$('#project-list');nav.replaceChildren();for(const p of projects){const b=element('button',p.name,p.id===project?.id?'project-link active':'project-link');b.addEventListener('click',()=>selectProject(p.id));nav.append(b);}if(!projects.length)nav.append(element('p','暂无项目，创建一个开始协作。','empty'));}
async function loadProjects(){projects=(await api('/api/projects')).projects;navigation();}
async function selectProject(id){
  try{const next=await api(`/api/projects/${id}`);const data=await api(`/api/projects/${id}/tasks`);project=next;$('#project-name').textContent=project.name;$('#new-task').disabled=false;$('#members-panel').hidden=false;$('#global-message').textContent='';navigation();renderBoard($('#board'),data.tasks,openTask);renderMembers();}
  catch(e){project=null;$('#board').replaceChildren();$('#project-name').textContent='项目不可访问';$('#members-panel').hidden=true;$('#new-task').disabled=true;if(e.code==='UNAUTHENTICATED')loggedOut();else message(e);}
}
function renderMembers(){const list=$('#members');list.replaceChildren();$('#member-form').hidden=project.ownerId!==user.id;for(const member of project.members){const li=element('li');li.append(element('span',member.username),element('small',member.id===project.ownerId?'负责人':member.canExecute?'可执行':'可讨论'));if(project.ownerId===user.id&&member.id!==project.ownerId){const remove=element('button','移除','quiet');remove.setAttribute('aria-label',`移除 ${member.username}`);remove.onclick=async()=>{remove.disabled=true;try{await api(`/api/projects/${project.id}/members/${member.id}`,{method:'DELETE'});await selectProject(project.id);}catch(e){message(e);remove.disabled=false;}};li.append(remove);}list.append(li);}}
async function openTask(id){
  try{view=await api(`/api/tasks/${id}`);renderTask(view,project,user);$('#comment-form').reset();$('#comment-form [name=body]').value=drafts.get(id)??'';$('#comment-error').textContent='';if(!$('#task-dialog').open)$('#task-dialog').showModal();}
  catch(e){if(['FORBIDDEN','UNAUTHENTICATED'].includes(e.code)){view=null;project=null;drafts.clear();$('#task-dialog').close();$('#comments').replaceChildren();$('#delivery').replaceChildren();$('#task-meta').replaceChildren();$('#task-title').textContent='';$('#comment-form').reset();$('#board').replaceChildren();$('#members').replaceChildren();$('#members-panel').hidden=true;$('#new-task').disabled=true;$('#project-name').textContent='项目不可访问';if(e.code==='UNAUTHENTICATED')loggedOut();else await loadProjects();}message(e);}
}
for(const button of document.querySelectorAll('[data-close]'))button.addEventListener('click',()=>document.getElementById(button.dataset.close).close());
$('#task-dialog').addEventListener('close',()=>{if(view)drafts.set(view.task.id,$('#comment-form [name=body]').value);});
$('#login-form').addEventListener('submit',event=>{event.preventDefault();submit(event.currentTarget,async()=>{const form=event.currentTarget;const session=await api('/api/login',{method:'POST',body:{username:form.elements.username.value,password:form.elements.password.value}});form.reset();await enter(session);});});
async function enter(session){user=session.user;setCsrf(session.csrf);$('#login-view').hidden=true;$('#workspace-view').hidden=false;$('#username').textContent=user.username;await loadProjects();if(projects.length)await selectProject(projects[0].id);else{$('#project-name').textContent='选择或创建项目';$('#new-task').disabled=true;$('#members-panel').hidden=true;renderBoard($('#board'),[],openTask);}}
$('#logout').onclick=async()=>{try{await api('/api/logout',{method:'POST',body:{}});loggedOut();}catch(e){message(e);}};
$('#new-project').onclick=()=>{$('#project-form').reset();$('#project-form .error').textContent='';$('#project-dialog').showModal();};
$('#project-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;submit(form,async()=>{const p=await api('/api/projects',{method:'POST',body:{name:form.elements.name.value}});$('#project-dialog').close();await loadProjects();await selectProject(p.id);});});
$('#member-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;submit(form,async()=>{await api(`/api/projects/${project.id}/members`,{method:'POST',body:{username:form.elements.username.value,canExecute:form.elements.canExecute.checked}});form.reset();await selectProject(project.id);});});
$('#new-task').onclick=()=>{if(!project)return;const form=$('#task-form');form.reset();form.querySelector('.error').textContent='';const select=form.elements.reviewerId;select.replaceChildren();for(const m of project.members){const option=element('option',m.username);option.value=m.id;select.append(option);}select.value=project.ownerId;$('#new-task-dialog').showModal();};
$('#task-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;submit(form,async()=>{const next=await api(`/api/projects/${project.id}/tasks`,{method:'POST',body:{title:form.elements.title.value,reviewerId:form.elements.reviewerId.value}});$('#new-task-dialog').close();await selectProject(project.id);await openTask(next.task.id);});});
$('#comment-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;submit(form,async()=>{if(!view)return;const {task}=view;drafts.set(task.id,form.elements.body.value);const intent=form.elements.intent.value,op=intent==='comment'?'comment':'review';view=await api(`/api/tasks/${task.id}/${op}`,{method:'POST',body:{version:task.version,body:form.elements.body.value,...(op==='review'?{intent}:{})}});drafts.delete(task.id);form.reset();renderTask(view,project,user);});});
$('#refresh-task').onclick=async()=>{if(view){drafts.set(view.task.id,$('#comment-form [name=body]').value);await openTask(view.task.id);}};
$('#cancel-task').onclick=async()=>{if(!view)return;try{view=await api(`/api/tasks/${view.task.id}/cancel`,{method:'POST',body:{version:view.task.version}});renderTask(view,project,user);}catch(e){$('#comment-error').textContent=errorMessage(e);}};
$('#refresh').onclick=async()=>{try{await loadProjects();if(project)await selectProject(project.id);}catch(e){if(e.code==='UNAUTHENTICATED')loggedOut();else message(e);}};
try{const session=await api('/api/session');if(session.user)await enter(session);}catch(e){$('#login-error').textContent=errorMessage(e);}
